name: Build release packages
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Use Node.js 12.x
      uses: actions/setup-node@v1
      with:
        node-version: 12.x
    - name: Cache Node.js modules
      uses: actions/cache@v2
      with:
        # npm cache files are stored in `~/.npm` on Linux/macOS
        path: ~/.npm
        key: ${{ runner.OS }}-node-${{ hashFiles('./yarn-lock.json') }}
        restore-keys: |
          ${{ runner.OS }}-node-
          ${{ runner.OS }}-
    - run: npm install -g yarn
    - run: yarn
    - run: yarn test --all

    # make build image for Linux
    - name: Build the Docker image
      run: docker build . -f misc/Dockerfile.builder.alpine -t builder:linux

    # run container to build package for linux
    - name: Build linux package
      run: docker run --rm -v $(pwd):/sxfiler:rw -w /sxfiler builder:linux /sxfiler/scripts/build.sh linux

    # package for linux
    - run: yarn package linux
    - uses: actions/upload-artifact@v1
      with:
        name: sxfiler_${{ github.sha }}_amd64
        path: dist/linux
